# -*- coding: utf-8 -*-

"""
/***************************************************************************
 fdsIsochrones
                                 A QGIS plugin
 create isochrones of fire progression from FDS outputs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-06-27
        copyright            : (C) 2023 by Eric Mueller
        email                : ericvmueller@gmail.com
 ***************************************************************************/
"""

__author__ = 'Eric Mueller'
__date__ = '2023-06-27'
__copyright__ = '(C) 2023 by Eric Mueller'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .fds_isochrones_provider import fdsIsochronesProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class fdsIsochronesPlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = fdsIsochronesProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
